#!/bin/env bash
source venv/bin/activate
# cd backend/ && python3 api/v1/app.py -> (flask)
cd backend/ && gunicorn -b 0.0.0.0:8000 api.v1.app:app --daemon
cd ../frontend/ && gunicorn -b 0.0.0.0:8001 app:app --daemon
