#!/bin/env bash
if ! [ -d "venv" ]; then
    echo -e "You dont Have The environment yet\n\t Creating One for you..."

    if ! command -v python3 &> /dev/null; then
        echo -e "What you don't have even python :(\n\tInstaling python for you.."
        sudo apt update
        sudo apt install python3
        sudo apt install python3.10-venv
        sudo apt install python3-pip
    fi
    if ! command -v gunicorn &> /dev/null; then
        pip install gunicorn
    fi
    if ! command -v mysql &> /dev/null; then
        echo -e "Installing mysql"
        sudo apt install mysql-server
        sudo service mysql start
        cat backend/savy.sql | mysql -u root -p

    fi

    python3 -m venv venv
fi

source venv/bin/activate
venv_size=$(du -s venv | cut -f1)

if [ -f "requirements.txt" ]; then
	if [ "$venv_size" -lt $((150 * 1024)) ]; then
		echo -e "\n\tInstalling requirements Just a sec.."
    		pip install -r requirements.txt
    		pip install --upgrade Flask Werkzeug
	fi
else
    echo -e "--E--(ERR) No requirements file Found :( Can't Continue!"
fi
# cd backend/ && python3 api/v1/app.py -> (flask)

env_root="$(which python3)"

cd backend/ && "$env_root" -m gunicorn -b 0.0.0.0:5005 api.v1.app:app --daemon
cd ../frontend/ && "$env_root" -m gunicorn -b 0.0.0.0:5000 app:app --daemon

if ps aux | grep gunicorn &> /dev/null; then
    echo -e "\n\t\t:)\n"
else
    echo -e "\n\t:("
fi
